varnish:
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: frontend=yes
  tty: true
  image: eeacms/varnish-eea-www
  external_links:
  - www-backend/anon:anon
  - www-backend/auth:auth
  - www-backend/download:download
  stdin_open: true
  environment:
  - BACKENDS=anon auth download
  - BACKENDS_PORT=8080
  - BACKENDS_PROBE_URL=${VARNISH_PROBE_URL}
  - BACKENDS_PROBE_TIMEOUT=${VARNISH_PROBE_TIMEOUT}
  - BACKENDS_PROBE_INTERVAL=${VARNISH_PROBE_INTERVAL}
  - BACKENDS_PROBE_WINDOW=${VARNISH_PROBE_WINDOW}
  - BACKENDS_PROBE_THRESHOLD=${VARNISH_PROBE_THRESHOLD}
  - BACKENDS_SAINT_MODE=true
  - DNS_ENABLED=true
apache:
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: frontend=yes
  tty: true
  image: eeacms/apache-eea-www
  links:
  - varnish:varnish
  volumes:
  - www-static-resources:/var/www-static-resources
  stdin_open: true
  volume_driver: convoy-gluster
