haproxy:
  external_links:
  - www-backend/anon:anon
  - www-backend/auth:auth
  labels:
    io.rancher.scheduler.affinity:host_label: frontend=yes
  tty: true
  image: eeacms/haproxy
  stdin_open: true
  environment:
  - BACKENDS=anon auth
  - BACKENDS_PORT=8080
  - DNS_ENABLED=true
varnish:
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: frontend=yes
  tty: true
  image: eeacms/varnish-eea-www
  links:
  - haproxy:haproxy
  stdin_open: true
apache:
  ports:
  - ${FRONTEND_PORT_ON_HOST}:80/tcp
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: frontend=yes
  tty: true
  image: eeacms/apache-eea-www
  links:
  - varnish:varnish
  volumes:
  - www-static-resources:/var/www-static-resources
  stdin_open: true
  volume_driver: convoy-gluster
