haproxy:
  expose:
  - 5000:5000
  external_links:
  - www-backend/anon:anon
  - www-backend/auth:auth
  labels:
    io.rancher.scheduler.affinity:host_label: frontend=yes
    io.rancher.loadbalancer.target.www-backend/anon: '8080'
    io.rancher.loadbalancer.target.www-backend/auth: '8080'
  tty: true
  image: rancher/load-balancer-service
  stdin_open: true
varnish:
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: frontend=yes
  tty: true
  image: eeacms/varnish-eea-www
  links:
  - haproxy:haproxy
  stdin_open: true
apache:
  ports:
  - ${FRONTEND_PORT_ON_HOST}:80/tcp
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: frontend=yes
  tty: true
  image: eeacms/apache-eea-www
  links:
  - varnish:varnish
  volumes:
  - www-static-resources:/var/www-static-resources
  stdin_open: true
  volume_driver: convoy-gluster
