varnish:
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: frontend=yes
  tty: true
  image: eeacms/varnish-eea-www
  external_links:
  - www-backend/anon:anon
  - www-backend/auth:auth
  - www-backend/download:download
  stdin_open: true
  environment:
  - BACKENDS=anon auth download
  - BACKENDS_PORT=8080
  - BACKENDS_PROBE_URL=/varnish_probe
  - BACKENDS_PROBE_TIMEOUT=3s
  - BACKENDS_PROBE_INTERVAL=30s
  - BACKENDS_PROBE_WINDOW=5
  - BACKENDS_PROBE_THRESHOLD=3
  - BACKENDS_SAINT_MODE=true
  - DNS_ENABLED=true
apache:
  ports:
  - ${FRONTEND_PORT_ON_HOST}:80/tcp
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: frontend=yes
  tty: true
  image: eeacms/apache-eea-www
  links:
  - varnish:varnish
  volumes:
  - www-static-resources:/var/www-static-resources
  stdin_open: true
  volume_driver: convoy-gluster
