version: '2'
services:
  rsync-client:
    environment:
      CRON_TASK_1: ${CRON_TASK_1}
      CRON_TASK_2: ${CRON_TASK_2}
      CRON_TASK_3: ${CRON_TASK_3}
      CRON_TASK_4: ${CRON_TASK_4}
      CRON_TASK_5: ${CRON_TASK_5}
      CRON_TASK_6: ${CRON_TASK_6}
      CRON_TASK_7: ${CRON_TASK_7}
      TZ: ${TZ}
    labels:
      io.rancher.scheduler.affinity:host_label: www=yes,sync=yes
    command:
    - client
    image: eeacms/rsync
    volumes:
    - www-blobstorage:/data/blobstorage
    - www-filestorage:/data/filestorage
    - www-downloads:/data/downloads
    - www-static-resources:/data/www-static-resources
    - www-eea-controlpanel:/data/eea.controlpanel
    - www-postgres-dump:/data/postgresql.backup
    - www-postgres-data:/var/lib/postgresql/data
    - www-postgres-archive:/var/lib/postgresql/archive
  rsync-server:
    ports:
    - 2222:22/tcp
    environment:
      SSH_AUTH_KEY_1: ${SSH_AUTH_KEY_1}
      SSH_AUTH_KEY_2: ${SSH_AUTH_KEY_2}
      TZ: ${TZ}
    labels:
      io.rancher.scheduler.affinity:host_label: www=yes,sync=yes
    command:
    - server
    image: eeacms/rsync
    volumes:
    - www-blobstorage:/data/blobstorage
    - www-filestorage:/data/filestorage
    - www-downloads:/data/downloads
    - www-static-resources:/data/www-static-resources
    - www-eea-controlpanel:/data/eea.controlpanel
    - www-postgres-dump:/data/postgresql.backup
    - www-postgres-data:/var/lib/postgresql/data
    - www-postgres-archive:/var/lib/postgresql/archive
volumes:
  www-blobstorage:
    external: true
    volume_driver: ${VOLUME_DRIVER}
  www-filestorage:
    external: true
    volume_driver: ${VOLUME_DRIVER}
  www-downloads:
    external: true
    volume_driver: ${VOLUME_DRIVER}
  www-static-resources:
    external: true
    volume_driver: ${VOLUME_DRIVER}
  www-eea-controlpanel:
    external: true
    volume_driver: ${VOLUME_DRIVER}
  www-postgres-dump:
    external: true
    volume_driver: ${VOLUME_DRIVER}
  www-postgres-data:
    external: true
  www-postgres-archive:
    external: true
