rsync-client:
  environment:
    CRON_TASK_1: ${CRON_TASK_1}
    CRON_TASK_2: ${CRON_TASK_2}
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: www=yes,sync=yes
  tty: true
  command:
  - client
  image: eeacms/rsync
  volumes:
  - www-blobstorage:/data/blobstorage
  - www-filestorage:/data/filestorage
  - www-downloads:/data/downloads
  - www-static-resources:/data/www-static-resources
  - www-eea-controlpanel:/data/eea.controlpanel
  - www-postgres-dump:/data/postgresql.backup
  stdin_open: true
  volume_driver: ${VOLUME_DRIVER}
rsync-server:
  ports:
  - 2222:22/tcp
  environment:
    SSH_AUTH_KEY_1: ${SSH_AUTH_KEY_1}
    SSH_AUTH_KEY_2: ${SSH_AUTH_KEY_2}
  log_driver: ''
  labels:
    io.rancher.sidekicks: rsync-data
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: www=yes,sync=yes
  tty: true
  command:
  - server
  log_opt: {}
  image: eeacms/rsync
  volumes:
  - www-blobstorage:/data/blobstorage
  - www-filestorage:/data/filestorage
  - www-downloads:/data/downloads
  - www-static-resources:/data/www-static-resources
  - www-eea-controlpanel:/data/eea.controlpanel
  - www-postgres-dump:/data/postgresql.backup
  volumes_from:
  - rsync-data
  stdin_open: true
  volume_driver: ${VOLUME_DRIVER}
rsync-data:
  image: busybox
  tty: true
  stdin_open: true
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
  volumes:
  - www-postgres-data:/var/lib/postgresql/data
  - www-postgres-archive:/var/lib/postgresql/archive
  command: ["chown", "-v", "-R", "999:999", "/var/lib/postgresql/data"]
