#
# PostgreSQL Live replica from production
#
postgres-upstream-replica:
  image: eeacms/postgres:${POSTGRES_VERSION}
  labels:
    io.rancher.sidekicks: postgres-upstream-replica-data
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: www=yes,sync=yes
  tty: true
  stdin_open: true
  environment:
  - POSTGRES_CRON_1=${POSTGRES_UPSTREM_CRON_1}
  volumes:
  - www-postgres-dump:/postgresql.backup
  volumes_from:
  - postgres-upstream-replica-data
  volume_driver: ${VOLUME_DRIVER}
postgres-upstream-replica-data:
  image: busybox
  tty: true
  stdin_open: true
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
  volumes:
  - /etc/localtime:/etc/localtime:ro
  - www-postgres-data:/var/lib/postgresql/data
  - www-postgres-archive:/var/lib/postgresql/archive
  command: ["chown", "-v", "-R", "999:999", "/var/lib/postgresql/"]
#
# PostgreSQL Master
#
postgres-master:
  image: eeacms/postgres:${POSTGRES_VERSION}
  labels:
    io.rancher.sidekicks: postgres-master-data
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: www=yes,db=yes
    io.rancher.scheduler.affinity:container_label_ne: postgres=yes
    postgres: 'yes'
  tty: true
  stdin_open: true
  environment:
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=postgres
  - POSTGRES_DBNAME=datafs zasync
  - POSTGRES_DBUSER=zope
  - POSTGRES_DBPASS=zope
  - POSTGRES_CONFIG_max_connections=${POSTGRES_MAX_CONNECTIONS}
  - POSTGRES_CONFIG_wal_level=hot_standby
  - POSTGRES_CONFIG_max_wal_senders=8
  - POSTGRES_CONFIG_wal_keep_segments=256
  - POSTGRES_CONFIG_hot_standby=on
  - POSTGRES_CRON_1=${POSTGRES_CRON_1}
  volumes:
  - www-postgres-dump:/postgresql.backup
  volumes_from:
  - postgres-master-data
  volume_driver: ${VOLUME_DRIVER}
postgres-master-data:
  image: busybox
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
  tty: true
  stdin_open: true
  volumes:
  - /etc/localtime:/etc/localtime:ro
  - www-postgres-master-data:/var/lib/postgresql/data
  command: ["chown", "-v", "-R", "999:999", "/var/lib/postgresql/data"]
#
# PostgreSQL Replica
#
postgres-replica:
  image: eeacms/postgres:${POSTGRES_VERSION}
  labels:
    io.rancher.sidekicks: postgres-replica-data
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: www=yes,db=yes
    io.rancher.scheduler.affinity:container_label_ne: postgres=yes
    postgres: 'yes'
  tty: true
  stdin_open: true
  links:
  - postgres-master:master
  environment:
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=postgres
  - POSTGRES_CONFIG_max_connections=${POSTGRES_MAX_CONNECTIONS}
  - POSTGRES_CONFIG_wal_level=hot_standby
  - POSTGRES_CONFIG_max_wal_senders=8
  - POSTGRES_CONFIG_wal_keep_segments=256
  - POSTGRES_CONFIG_hot_standby=on
  - POSTGRES_REPLICATE_FROM=master
  volumes:
  - www-postgres-dump:/postgresql.backup
  volumes_from:
  - postgres-replica-data
  volume_driver: ${VOLUME_DRIVER}
postgres-replica-data:
  image: busybox
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
  tty: true
  stdin_open: true
  volumes:
  - /etc/localtime:/etc/localtime:ro
  - www-postgres-replica-data:/var/lib/postgresql/data
  command: ["chown", "-v", "-R", "999:999", "/var/lib/postgresql/data"]
