memcached:
  environment:
    MEMCACHED_MEMORY: '${MEMCACHED_MEMORY}'
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label: db=yes
  tty: true
  image: eeacms/memcached
  stdin_open: true
relcached:
  environment:
    MEMCACHED_MEMORY: '${MEMCACHED_MEMORY}'
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label: db=yes
  tty: true
  image: eeacms/memcached
  stdin_open: true
postgres:
  image: rancher/external-service
