version: '2'
services:
  postgres-upstream-replica:
    scale: ${POSTGRES_UPSTREAM_SCALE}
    start_on_create: true
    health_check:
      port: 5432
      interval: 2000
      unhealthy_threshold: 3
      strategy: none
      response_timeout: 2000
      healthy_threshold: 2
  postgres-master:
    scale: ${POSTGRES_MASTER_SCALE}
    start_on_create: true
    external_ips:
    - ${POSTGRES_MASTER_IP}
    health_check:
      port: 5432
      interval: 2000
      unhealthy_threshold: 3
      strategy: none
      response_timeout: 2000
      healthy_threshold: 2
  postgres-replica:
    scale: ${POSTGRES_REPLICA_SCALE}
    start_on_create: true
    health_check:
      port: 5432
      interval: 2000
      unhealthy_threshold: 3
      strategy: none
      response_timeout: 2000
      healthy_threshold: 2
