version: '2'
services:
  postgres-upstream-replica:
    image: eeacms/postgres:${POSTGRES_VERSION}
    labels:
      io.rancher.scheduler.affinity:host_label: www=yes,sync=yes
    environment:
      POSTGRES_CRON_1: ${POSTGRES_UPSTREM_CRON_1}
      TZ: ${TZ}
    volumes:
    - www-postgres-dump:/postgresql.backup
    - www-postgres-data:/var/lib/postgresql/data
    - www-postgres-upstream-archive:/var/lib/postgresql/archive
  postgres-master:
    image: eeacms/postgres:${POSTGRES_VERSION}
    labels:
      io.rancher.scheduler.affinity:host_label: www=yes,db=yes,db-master=yes
      io.rancher.scheduler.affinity:container_label_ne: postgres=yes
      postgres: 'yes'
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DBNAME: "datafs zasync"
      POSTGRES_DBUSER: "zope"
      POSTGRES_DBPASS: "zope"
      POSTGRES_CONFIG_max_connections: "150"
      POSTGRES_CONFIG_wal_level: "hot_standby"
      POSTGRES_CONFIG_max_wal_senders: "8"
      POSTGRES_CONFIG_wal_keep_segments: "256"
      POSTGRES_CONFIG_hot_standby: "on"
      POSTGRES_CONFIG_archive_mode: "on"
      POSTGRES_CONFIG_archive_command: " 'cp %p /var/lib/postgresql/archive/%f' "
      POSTGRES_CRON_1: ${POSTGRES_CRON_1}
      TZ: ${TZ}
    volumes:
    - www-postgres-data:/var/lib/postgresql/data
    - www-postgres-dump:/postgresql.backup
    - www-postgres-replication-archive:/var/lib/postgresql/archive
  postgres-replica:
    image: eeacms/postgres:${POSTGRES_VERSION}
    labels:
      io.rancher.scheduler.affinity:host_label: www=yes,db=yes,db-replica=yes
      io.rancher.scheduler.affinity:container_label_ne: postgres=yes
      postgres: 'yes'
    links:
    - postgres-master:master
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_CONFIG_max_connections: "150"
      POSTGRES_CONFIG_wal_level: "hot_standby"
      POSTGRES_CONFIG_max_wal_senders: "8"
      POSTGRES_CONFIG_wal_keep_segments: "256"
      POSTGRES_CONFIG_hot_standby: "on"
      POSTGRES_REPLICATE_FROM: "master"
      RECOVERY_CONFIG_standby_mode: "on"
      RECOVERY_CONFIG_primary_conninfo: " 'host=master port=5432 user=postgres' "
      RECOVERY_CONFIG_restore_command: " 'cp /var/lib/postgresql/archive/%f %p' "
      RECOVERY_CONFIG_archive_cleanup_command: " 'pg_archivecleanup /var/lib/postgresql/archive %r' "
      RECOVERY_CONFIG_trigger_file: " '/tmp/touch_me_to_promote_to_me_master' "
      TZ: ${TZ}
    volumes:
    - www-postgres-data:/var/lib/postgresql/data
    - www-postgres-dump:/postgresql.backup
    - www-postgres-replication-archive:/var/lib/postgresql/archive
volumes:
  www-postgres-data:
    external: true
  www-postgres-dump:
    external: true
    volume_driver: ${VOLUME_DRIVER}
  www-postgres-upstream-archive:
    external: true
    volume_driver: ${VOLUME_DRIVER}
  www-postgres-replication-archive:
    external: true
    volume_driver: ${VOLUME_DRIVER}
