version: '2'
services:
  apache:
    image: eeacms/apache-eea-www:${APACHE_VERSION}
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: www=yes,frontend=yes
      io.rancher.scheduler.affinity:container_label_soft_ne: eu.europa.eea.apache=yes
      eu.europa.eea.apache: "yes"
    environment:
      SERVER_NAME: "${SERVER_NAME}"
      APACHE_MODULES: "mime_magic_module unique_id_module data_module unique_id_module remoteip_module negotiation_module"
      APACHE_INCLUDE: "conf/extra/httpd-languages.conf conf/extra/httpd-default.conf"
      APACHE_TIMEOUT: "120"
      APACHE_KEEPALIVE_TIMEOUT: "8"
      TRACEVIEW: "${TRACEVIEW}"
      TZ: "${TZ}"
    depends_on:
    - varnish
    volumes:
    - www-static-resources:/var/www-static-resources
  varnish:
    image: eeacms/varnish-eea-www:${VARNISH_VERSION}
    ports:
    - "6081"
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: www=yes,frontend=yes
      io.rancher.scheduler.affinity:container_label_soft_ne: eu.europa.eea.varnish=yes
      eu.europa.eea.varnish: "yes"
    depends_on:
    - anon
    - auth
    - download
    environment:
      CACHE_SIZE: "${VARNISH_CACHE_SIZE}"
      PARAM_VALUE: "${VARNISH_PARAMS}"
      TZ: "${TZ}"
      BACKENDS: "anon auth download"
      BACKENDS_PORT: "8080"
      BACKENDS_PROBE_ENABLED: "false"
      DNS_ENABLED: "true"
  auth:
    image: eeacms/haproxy:${HAPROXY_VERSION}
    ports:
    - "7990:8080"
    - "1936"
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: www=yes,frontend=yes
      io.rancher.scheduler.affinity:container_label_soft_ne: eu.europa.eea.auth=yes
      eu.europa.eea.auth: "yes"
    depends_on:
    - auth-instance
    environment:
      FRONTEND_PORT: "8080"
      BACKENDS: "auth-instance"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "True"
      TZ: "Europe/Copenhagen"
      HTTPCHK: "GET /health.check"
      INTER: "20s"
      DOWN_INTER: "5s"
      FAST_INTER: "15s"
      TIMEOUT_CLIENT: "5s"
      TIMEOUT_SERVER: "120s"
      TIMEOUT_CLIENT: "120s"
  anon:
    image: eeacms/haproxy:${HAPROXY_VERSION}
    ports:
    - "7994:8080"
    - "1936"
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: www=yes,frontend=yes
      io.rancher.scheduler.affinity:container_label_soft_ne: eu.europa.eea.anon=yes
      eu.europa.eea.anon: "yes"
    depends_on:
    - anon-instance
    environment:
      FRONTEND_PORT: "8080"
      BACKENDS: "anon-instance"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "True"
      TZ: "Europe/Copenhagen"
      HTTPCHK: "GET /health.check"
      INTER: "5s"
      TIMEOUT_CLIENT: "5s"
      TIMEOUT_SERVER: "120s"
      TIMEOUT_CLIENT: "120s"
  download:
    image: eeacms/haproxy:${HAPROXY_VERSION}
    ports:
    - "7998:8080"
    - "1936"
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: www=yes,frontend=yes
      io.rancher.scheduler.affinity:container_label_soft_ne: eu.europa.eea.download=yes
      eu.europa.eea.download: "yes"
    depends_on:
    - download-instance
    environment:
      FRONTEND_PORT: "8080"
      BACKENDS: "download-instance"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "True"
      TZ: "Europe/Copenhagen"
      HTTPCHK: "GET /health.check"
      INTER: "5s"
      TIMEOUT_CLIENT: "5s"
      TIMEOUT_SERVER: "120s"
      TIMEOUT_CLIENT: "120s"
  anon-instance:
    image: eeacms/www:${KGS_VERSION}
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: www=yes,backend=yes
      io.rancher.scheduler.affinity:container_label_soft_ne: eu.europa.eea.anon-instance=yes
      eu.europa.eea.anon-instance: "yes"
    environment:
      ZOPE_MODE: "rel_client"
      ZOPE_THREADS: "2"
      ZOPE_FORCE_CONNECTION_CLOSE: 'off'
      GRAYLOG: "${GRAYLOG}"
      GRAYLOG_FACILITY: "${GRAYLOG_FACILITY}"
      WARMUP_HEALTH_THRESHOLD: "${WARMUP}"
      TRACEVIEW: "${TRACEVIEW}"
      RABBITMQ_USER: "${RABBITMQ_USER}"
      RABBITMQ_PASS: "${RABBITMQ_PASS}"
      TZ: "${TZ}"
    depends_on:
    - postgres
    - relcached
    - memcached
    - rabbitmq
    volumes:
    - www-blobstorage:/data/blobstorage
    - www-downloads:/data/downloads
    - www-static-resources:/data/www-static-resources
    - www-eea-controlpanel:/data/eea.controlpanel
    - www-anon-data:/data
  auth-instance:
    image: eeacms/www:${KGS_VERSION}
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: www=yes,backend=yes
      io.rancher.scheduler.affinity:container_label_soft_ne: eu.europa.eea.auth-instance=yes
      eu.europa.eea.auth-instance: "yes"
    environment:
      ZOPE_MODE: "rel_client"
      ZOPE_THREADS: "2"
      GRAYLOG: "${GRAYLOG}"
      GRAYLOG_FACILITY: "${GRAYLOG_FACILITY}"
      WARMUP_HEALTH_THRESHOLD: "${WARMUP}"
      TRACEVIEW: "${TRACEVIEW}"
      RABBITMQ_USER: "${RABBITMQ_USER}"
      RABBITMQ_PASS: "${RABBITMQ_PASS}"
      TZ: "${TZ}"
    depends_on:
    - postgres
    - relcached
    - memcached
    - rabbitmq
    volumes:
    - www-blobstorage:/data/blobstorage
    - www-downloads:/data/downloads
    - www-static-resources:/data/www-static-resources
    - www-eea-controlpanel:/data/eea.controlpanel
    - www-auth-data:/data
  download-instance:
    image: eeacms/www:${KGS_VERSION}
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: www=yes,backend=yes
      io.rancher.scheduler.affinity:container_label_soft_ne: eu.europa.eea.download-instance=yes
      eu.europa.eea.download-instance: "yes"
    environment:
      ZOPE_MODE: "rel_client"
      ZOPE_THREADS: "2"
      ZOPE_FORCE_CONNECTION_CLOSE: 'off'
      GRAYLOG: "${GRAYLOG}"
      GRAYLOG_FACILITY: "${GRAYLOG_FACILITY}"
      WARMUP_HEALTH_THRESHOLD: "${WARMUP}"
      TRACEVIEW: "${TRACEVIEW}"
      RABBITMQ_USER: "${RABBITMQ_USER}"
      RABBITMQ_PASS: "${RABBITMQ_PASS}"
      TZ: "${TZ}"
    depends_on:
    - postgres
    - relcached
    - memcached
    - rabbitmq
    volumes:
    - www-blobstorage:/data/blobstorage
    - www-downloads:/data/downloads
    - www-static-resources:/data/www-static-resources
    - www-eea-controlpanel:/data/eea.controlpanel
    - www-download-data:/data
  async-instance:
    image: eeacms/www:${KGS_VERSION}
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: www=yes,backend=yes
      io.rancher.scheduler.affinity:container_label_soft_ne: eu.europa.eea.async-instance=yes
      eu.europa.eea.async-instance: "yes"
    environment:
      ZOPE_MODE: "rel_async"
      ZOPE_THREADS: "2"
      ZOPE_FAST_LISTEN: 'on'
      GRAYLOG: "${GRAYLOG}"
      GRAYLOG_FACILITY: "${GRAYLOG_FACILITY}"
      WARMUP_HEALTH_THRESHOLD: "${WARMUP}"
      TRACEVIEW: "${TRACEVIEW}"
      RABBITMQ_USER: "${RABBITMQ_USER}"
      RABBITMQ_PASS: "${RABBITMQ_PASS}"
      TZ: "${TZ}"
    depends_on:
    - postgres
    - relcached
    - memcached
    - rabbitmq
    volumes:
    - www-blobstorage:/data/blobstorage
    - www-downloads:/data/downloads
    - www-static-resources:/data/www-static-resources
    - www-eea-controlpanel:/data/eea.controlpanel
    - www-async-data:/data
  memcached:
    environment:
      TZ: "${TZ}"
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: www=yes,cache=yes
      io.rancher.scheduler.affinity:container_label_soft_ne: eu.europa.eea.memcached=yes
      eu.europa.eea.memcached: "yes"
    image: memcached:${MEMCACHED_VERSION}
    command:
    - "-m"
    - "${MEMCACHED_MEMORY}"
  relcached:
    environment:
      TZ: "${TZ}"
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: www=yes,cache=yes
      io.rancher.scheduler.affinity:container_label_soft_ne: eu.europa.eea.relcached=yes
      eu.europa.eea.relcached: "yes"
    image: memcached:${MEMCACHED_VERSION}
    command:
    - "-m"
    - "${MEMCACHED_MEMORY}"
  rabbitmq:
    image: rancher/external-service
  postgres:
    image: rancher/dns-service
    external_links:
    - www-db/postgres-master:postgres
volumes:
  www-anon-data:
    per_container: true
  www-download-data:
    per_container: true
  www-auth-data:
    per_container: true
  www-async-data:
    per_container: true
  www-blobstorage:
    external: true
    volume_driver: ${VOLUME_DRIVER}
  www-downloads:
    external: true
    volume_driver: ${VOLUME_DRIVER}
  www-static-resources:
    external: true
    volume_driver: ${VOLUME_DRIVER}
  www-eea-controlpanel:
    external: true
    volume_driver: ${VOLUME_DRIVER}
