#
# Frontend
#
apache:
  scale: ${APACHE_SCALE}
  health_check:
    port: 80
    interval: 30000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 2
    response_timeout: 2000
varnish:
  scale: ${VARNISH_SCALE}
  health_check:
    port: 6081
    interval: 30000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 2
    response_timeout: 2000
#
# Plone backends
#
anon:
  scale: ${ANON_SCALE}
  health_check:
    port: 8080
    interval: 5000
    initializing_timeout: 300000
    unhealthy_threshold: 3
    strategy: recreate
    request_line: GET "/health.check" "HTTP/1.0"
    response_timeout: 3000
    healthy_threshold: 2
anon-data:
  scale: 1
download:
  scale: ${DOWNLOAD_SCALE}
  health_check:
    port: 8080
    interval: 5000
    initializing_timeout: 300000
    unhealthy_threshold: 3
    strategy: recreate
    request_line: GET "/health.check" "HTTP/1.0"
    response_timeout: 3000
    healthy_threshold: 2
download-data:
  scale: 1
auth:
  scale: ${AUTH_SCALE}
  health_check:
    port: 8080
    interval: 5000
    initializing_timeout: 300000
    unhealthy_threshold: 3
    strategy: recreate
    request_line: GET "/health.check" "HTTP/1.0"
    response_timeout: 3000
    healthy_threshold: 2
auth-data:
  scale: 1
async:
  scale: ${ASYNC_SCALE}
  health_check:
    port: 8080
    interval: 5000
    initializing_timeout: 300000
    unhealthy_threshold: 3
    strategy: recreate
    request_line: GET "/health.check" "HTTP/1.0"
    response_timeout: 3000
    healthy_threshold: 2
async-data:
  scale: 1
#
# Cache
#
memcached:
  scale: ${MEMCACHED_SCALE}
  health_check:
    port: 11211
    interval: 2000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2
relcached:
  scale: ${RELCACHED_SCALE}
  health_check:
    port: 11211
    interval: 2000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2
