version: '2'
services:
  apache:
    scale: ${APACHE_SCALE}
    upgrade_strategy:
      start_first: true
    health_check:
      port: 80
      interval: 40000
      initializing_timeout: 600000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 3000
  varnish:
    scale: ${VARNISH_SCALE}
    upgrade_strategy:
      start_first: true
    health_check:
      port: 6081
      interval: 40000
      initializing_timeout: 600000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 3000
  anon:
    scale: ${ANON_SCALE}
    upgrade_strategy:
      start_first: true
    health_check:
      port: 8080
      interval: 40000
      initializing_timeout: 600000
      unhealthy_threshold: 3
      strategy: recreate
      request_line: GET "/health.check" "HTTP/1.0"
      response_timeout: 15000
      healthy_threshold: 2
  download:
    scale: ${DOWNLOAD_SCALE}
    upgrade_strategy:
      start_first: true
    health_check:
      port: 8080
      interval: 40000
      initializing_timeout: 600000
      unhealthy_threshold: 3
      strategy: recreate
      request_line: GET "/health.check" "HTTP/1.0"
      response_timeout: 15000
      healthy_threshold: 2
  auth:
    scale: ${AUTH_SCALE}
    upgrade_strategy:
      start_first: true
    health_check:
      port: 8080
      interval: 40000
      initializing_timeout: 600000
      unhealthy_threshold: 3
      strategy: recreate
      request_line: GET "/health.check" "HTTP/1.0"
      response_timeout: 15000
      healthy_threshold: 2
  async:
    scale: ${ASYNC_SCALE}
    upgrade_strategy:
      start_first: true
    health_check:
      port: 8080
      interval: 40000
      initializing_timeout: 600000
      unhealthy_threshold: 3
      strategy: recreate
      request_line: GET "/health.check" "HTTP/1.0"
      response_timeout: 15000
      healthy_threshold: 2
  memcached:
    scale: ${MEMCACHED_SCALE}
    upgrade_strategy:
      start_first: true
    health_check:
      port: 11211
      interval: 40000
      initializing_timeout: 600000
      unhealthy_threshold: 3
      strategy: recreate
      response_timeout: 3000
      healthy_threshold: 2
  relcached:
    scale: ${RELCACHED_SCALE}
    upgrade_strategy:
      start_first: true
    health_check:
      port: 11211
      interval: 40000
      initializing_timeout: 600000
      unhealthy_threshold: 3
      strategy: recreate
      response_timeout: 3000
      healthy_threshold: 2
  rabbitmq:
    hostname: ${RABBITMQ_HOST}
