#
# Frontend
#
apache:
  health_check:
    port: 80
    interval: 30000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 2
    response_timeout: 2000
varnish:
  health_check:
    port: 6081
    interval: 30000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 2
    response_timeout: 2000
#
# Plone backends
#
anon:
  scale: ${ANON_SCALE}
  health_check:
    port: 8080
    interval: 5000
    initializing_timeout: 300000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 3000
    healthy_threshold: 2
download:
  scale: ${DOWNLOAD_SCALE}
  health_check:
    port: 8080
    interval: 5000
    initializing_timeout: 300000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 3000
    healthy_threshold: 2
auth:
  scale: ${AUTH_SCALE}
  health_check:
    port: 8080
    interval: 5000
    initializing_timeout: 300000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 3000
    healthy_threshold: 2
async:
  scale: ${ASYNC_SCALE}
  health_check:
    port: 8080
    interval: 5000
    initializing_timeout: 300000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 3000
    healthy_threshold: 2
#
# Cache
#
memcached:
  health_check:
    port: 11211
    interval: 2000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2
relcached:
  health_check:
    port: 11211
    interval: 2000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2
