version: '2'
services:
  debug:
    image: eeacms/www:${KGS_VERSION}
    ports:
    - "8080"
    environment:
      ZOPE_MODE: rel_client
      WARMUP_HEALTH_THRESHOLD: 1
      TZ: ${TZ}
    links:
    - www-eea/postgres:postgres
    - www-eea/relcached:relcached
    - www-eea/memcached:memcached
    labels:
      io.rancher.scheduler.affinity:host_label: www=yes,backend=yes
      io.rancher.scheduler.affinity:container_label_soft_ne: eu.europa.eea.debug=yes
      eu.europa.eea.debug: "yes"
    volumes:
    - www-blobstorage:/data/blobstorage
    - www-downloads:/data/downloads
    - www-static-resources:/data/www-static-resources
    - www-eea-controlpanel:/data/eea.controlpanel
    - www-debug-data:/data
    tty: true
    stdin_open: true
    command: ["cat"]

volumes:
  www-debug-data:
    per_container: true
  www-blobstorage:
    external: true
    volume_driver: ${VOLUME_DRIVER}
  www-downloads:
    external: true
    volume_driver: ${VOLUME_DRIVER}
  www-static-resources:
    external: true
    volume_driver: ${VOLUME_DRIVER}
  www-eea-controlpanel:
    external: true
    volume_driver: ${VOLUME_DRIVER}
