version: '2'
services:
  debug:
    image: eeacms/www:${KGS_VERSION}
    ports:
    - "8080"
    environment:
      ZOPE_MODE: "rel_client"
      ZOPE_THREADS: "2"
      GRAYLOG: "${GRAYLOG}"
      GRAYLOG_FACILITY: "${GRAYLOG_FACILITY}"
      WARMUP_HEALTH_THRESHOLD: "${WARMUP}"
      TRACEVIEW: "${TRACEVIEW}"
      RABBITMQ_USER: "${RABBITMQ_USER}"
      RABBITMQ_PASS: "${RABBITMQ_PASS}"
      TZ: "${TZ}"
    depends_on:
    - postgres
    - relcached
    - memcached
    - rabbitmq
    labels:
      io.rancher.scheduler.affinity:host_label: www=yes,backend=yes
      io.rancher.scheduler.affinity:container_label_soft_ne: eu.europa.eea.debug=yes
      eu.europa.eea.debug: "yes"
    volumes:
    - www-blobstorage:/data/blobstorage
    - www-downloads:/data/downloads
    - www-static-resources:/data/www-static-resources
    - www-eea-controlpanel:/data/eea.controlpanel
    - www-debug-data:/data
    tty: true
    stdin_open: true
    command: ["cat"]
  postgres:
    image: rancher/dns-service
    external_links:
    - www-postgres/master:postgres
  memcached:
    image: rancher/dns-service
    external_links:
    - www-eea/memcached:memcached
  relcached:
    image: rancher/dns-service
    external_links:
    - www-eea/relcached:relcached
  rabbitmq:
    image: rancher/dns-service
    external_links:
    - www-eea/rabbitmq:rabbitmq

volumes:
  www-debug-data:
    per_container: true
  www-blobstorage:
    external: true
    volume_driver: ${VOLUME_DRIVER}
  www-downloads:
    external: true
    volume_driver: ${VOLUME_DRIVER}
  www-static-resources:
    external: true
    volume_driver: ${VOLUME_DRIVER}
  www-eea-controlpanel:
    external: true
    volume_driver: ${VOLUME_DRIVER}
