version: '2'
catalog:
  name: "EEA WWW - Volumes"
  description: "Prepare Docker volumes needed by EEA WWW"
  version: "1.0-rancher1"
  uuid: "www-volumes-0"
  minimum_rancher_version: "v1.2.0"
  questions:
  - variable: "NFS_VOLUME_DRIVER"
    label: "NFS Volume Driver"
    description: "Docker volume driver to be used for shared volumes"
    default: "rancher-nfs"
    required: true
    type: "enum"
    options:
    - "rancher-nfs"
  - variable: "DB_VOLUME_DRIVER"
    label: "DB Volume Driver"
    description: "Docker volume driver to be used for PostgreSQL DB volumes"
    default: "local"
    required: true
    type: "enum"
    options:
    - "local"
  - variable: "VOLUME_HOST_LABELS"
    label: "Schedule services on hosts with the following host labels"
    description: "Comma separated list of host labels (e.g. key1=value1, key2=value2) to be used for scheduling services"
    default: "www=yes,db=yes"
    type: "string"
