.catalog:
    name: "Convoy GlusterFS"
    version: "v0.2"
    description: "Convoy GlusterFS - Docker volume plugin"
    questions:
     - variable: "VOLUME_POOL"
       description: "Name of the GlusterFS Volume"
       label: "GlusterFS Volume"
       required: true
       type: "string"
       default: my_vol
     - variable: "GLUSTERFS_SERVICE"
       label: "GlusterFS Service"
       type: "service"
       required: true
       description: Service that is running GlusterFS

convoy-gluster:
    metadata:
        volume_pool: "gluster_storage"
    health_check:
        request_line: GET /healthcheck HTTP/1.0
        port: 10241
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2

convoy-gluster-storagepool:
    scale: 1
    health_check:
        request_line: GET /healthcheck HTTP/1.0
        port: 10241
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2
