fileserver:
  image: eeacms/os-docker-vm:v2.0
  env_file:
  - .cloudaccess
  - .secret
  environment:
    INSTANCE_FLAVOR: "e2standard.x4"
    INSTANCE_DOCKER_VOLUME_SIZE: "500"
    INSTANCE_DOCKER_VOLUME_TYPE: "top"
    IMAGE_NAME: "EEA-docker-generic-v2.2"

db:
  image: eeacms/os-docker-vm:v2.0
  env_file:
  - .cloudaccess
  - .secret
  environment:
    INSTANCE_FLAVOR: "e2standard.x5"
    INSTANCE_DOCKER_VOLUME_SIZE: "128"
    INSTANCE_DOCKER_VOLUME_TYPE: "top"
    IMAGE_NAME: "EEA-docker-generic-v2.2"

plone:
  image: eeacms/os-docker-vm:v2.0
  env_file:
  - .cloudaccess
  - .secret
  environment:
    INSTANCE_FLAVOR: "e2standard.x6"
    INSTANCE_DOCKER_VOLUME_SIZE: "10"
    INSTANCE_DOCKER_VOLUME_TYPE: "top"
    IMAGE_NAME: "EEA-docker-generic-v2.2"

frontend:
  image: eeacms/os-docker-vm:v2.0
  env_file:
  - .cloudaccess
  - .secret
  environment:
    INSTANCE_FLAVOR: "e2standard.x6"
    INSTANCE_DOCKER_VOLUME_SIZE: "10"
    INSTANCE_DOCKER_VOLUME_TYPE: "top"
    IMAGE_NAME: "EEA-docker-generic-v2.2"
