############################
# Add 1 hosts for fileserver
############################

fileserver1:
  extends:
    file: base-flavors.yml
    service: fileserver
  environment:
    INSTANCE_NAME: "dev-mil-www-nfs"

####################
# Add 2 hosts for DB
####################

db1:
  extends:
    file: base-flavors.yml
    service: db
  environment:
    INSTANCE_NAME: "dev-mil-db-1"

db2:
  extends:
    file: base-flavors.yml
    service: db
  environment:
    INSTANCE_NAME: "dev-mil-db-2"


###########################
# Add 3 hosts for Plone app
###########################

plone1:
  extends:
    file: base-flavors.yml
    service: plone
  environment:
    INSTANCE_NAME: "dev-mil-plone-1"

plone2:
  extends:
    file: base-flavors.yml
    service: plone
  environment:
    INSTANCE_NAME: "dev-mil-plone-2"

plone3:
  extends:
    file: base-flavors.yml
    service: plone
  environment:
    INSTANCE_NAME: "dev-mil-plone-3"

#########################
# Add 1 host for frontend
#########################

frontend:
  extends:
    file: base-flavors.yml
    service: frontend
  environment:
    INSTANCE_NAME: "dev-mil-frontend-1"
