#
# PostgreSQL Master
#
postgres-master:
  image: eeacms/postgres:${POSTGRES_VERSION}
  labels:
    io.rancher.scheduler.affinity:host_label: www=yes,db=yes
    io.rancher.scheduler.affinity:container_label_ne: postgres=yes
    postgres: 'yes'
  environment:
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres"
    POSTGRES_DBNAME: "datafs zasync"
    POSTGRES_DBUSER: "zope"
    POSTGRES_DBPASS: "zope"
    POSTGRES_CONFIG_max_connections: "150"
    POSTGRES_CONFIG_wal_level: "hot_standby"
    POSTGRES_CONFIG_max_wal_senders: "8"
    POSTGRES_CONFIG_wal_keep_segments: "256"
    POSTGRES_CONFIG_hot_standby: "on"
    POSTGRES_CONFIG_archive_mode: "on"
    POSTGRES_CONFIG_archive_command: " 'cp %p /var/lib/postgresql/archive/%f' "
    POSTGRES_CRON_1: ${POSTGRES_CRON_1}
    TZ: ${TZ}
  volumes:
  - www-postgres-dump:/postgresql.backup
  - www-postgres-replication-archive:/var/lib/postgresql/archive
  - www-postgres-master-data:/var/lib/postgresql/data
  volume_driver: ${VOLUME_DRIVER}
