plone:
  scale: 2
  health_check:
    port: 8080
    interval: 30000
    unhealthy_threshold: 3
    strategy: none
    response_timeout: 3000
    healthy_threshold: 2
async:
  scale: 1
  health_check:
    port: 8080
    interval: 30000
    initializing_timeout: 300000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 3000
    healthy_threshold: 2
