haproxy:
  image: eeacms/haproxy
  ports:
  - 80:5000
  - 1936:1936
  links:
  - plone
  environment:
  - BACKENDS_PORT=8080
  - SERVICE_NAMES=plone
  volumes:
  - /etc/localtime:/etc/localtime:ro

memcached:
  image: eeacms/memcached
  environment:
  - MEMCACHED_MEMORY=2048
  volumes:
  - /etc/localtime:/etc/localtime:ro

relcached:
  image: eeacms/memcached
  environment:
  - MEMCACHED_MEMORY=2048
  volumes:
  - /etc/localtime:/etc/localtime:ro

plone:
  image: eeacms/www:devel
  ports:
  - "4444:4444"
  links:
  - memcached
  - relcached
  - postgres
  volumes:
  - ./src:/plone/instance/src
  - /etc/localtime:/etc/localtime:ro
  - /var/blobstorage/blobs:/data/blobstorage
  - /var/blobstorage/downloads:/data/downloads
  environment:
  - ZOPE_MODE=rel_client
  command: ['fg']

async:
  image: eeacms/www:devel
  links:
  - memcached
  - relcached
  - postgres
  volumes:
  - ./src:/plone/instance/src
  - /etc/localtime:/etc/localtime:ro
  - /var/blobstorage/blobs:/data/blobstorage
  - /var/blobstorage/downloads:/data/downloads
  environment:
  - ZOPE_MODE=rel_async
  command: ['fg']

postgres:
  image: eeacms/postgres:9.4
  environment:
    POSTGRES_DBNAME: datafs zasync
    POSTGRES_DBPASS: zope
    POSTGRES_DBUSER: zope
  volumes:
  - ./backup:/postgresql.backup:z
  - /etc/localtime:/etc/localtime:ro
  volumes_from:
  - postgres_data

postgres_data:
  command: ["chown", "-v", "-R", "999:999", "/var/lib/postgresql/data"]
  image: busybox
  volumes:
  - /var/lib/postgresql/data
