haproxy:
  ports:
  - 80:5000
  image: eeacms/haproxy
  links:
  - plone
  environment:
    BACKENDS_PORT: '8080'
    SERVICE_NAMES: 'plone'
  volumes:
  - /etc/localtime:/etc/localtime:ro

memcached:
  environment:
    MEMCACHED_MEMORY: '2048'
  image: eeacms/memcached
  volumes:
  - /etc/localtime:/etc/localtime:ro

relcached:
  environment:
    MEMCACHED_MEMORY: '2048'
  image: eeacms/memcached
  volumes:
  - /etc/localtime:/etc/localtime:ro

plone:
  image: eeacms/plone-eea-www:devel
  links:
  - memcached
  - relcached
  - postgres
  volumes:
  - /etc/localtime:/etc/localtime:ro
  - /var/blobstorage/blobs:/data/blobs
  - /var/blobstorage/downloads:/data/downloads
  environment:
  - DEBUG=on

async:
  image: eeacms/plone-eea-www:devel-async
  links:
  - memcached
  - relcached
  - postgres
  volumes:
  - /etc/localtime:/etc/localtime:ro
  - /var/blobstorage/blobs:/data/blobs
  - /var/blobstorage/downloads:/data/downloads
  environment:
  - DEBUG=on

postgres:
  image: eeacms/postgres
  environment:
    POSTGRES_DBNAME: datafs zasync
    POSTGRES_DBPASS: zope
    POSTGRES_DBUSER: zope
  volumes:
  - ./backup:/postgresql.backup:z
  - /etc/localtime:/etc/localtime:ro
  volumes_from:
  - postgres_data

postgres_data:
  command: ["chown", "-v", "-R", "999:999", "/var/lib/postgresql/data"]
  image: busybox
  volumes:
  - /var/lib/postgresql/data
