memcached:
  environment:
    MEMCACHED_MEMORY: '2048'
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: frontend=yes
  tty: true
  image: eeacms/memcached
  stdin_open: true
haproxy:
  ports:
  - 5000:5000
  external_links:
  - www-backend/plone:plone
  labels:
    io.rancher.scheduler.affinity:host_label: frontend=yes
    io.rancher.loadbalancer.target.www-backend/plone: '8080'
  tty: true
  image: rancher/load-balancer-service
  stdin_open: true
varnish:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: frontend=yes
  tty: true
  image: eeacms/varnish-eea-www
  links:
  - haproxy:haproxy
  stdin_open: true
apache:
  ports:
  - 80:80/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: frontend=yes
  tty: true
  image: eeacms/apache-eea-www
  links:
  - varnish:varnish
  volumes:
  - www-static-resources:/var/www-static-resources
  stdin_open: true
  volume_driver: convoy-nfs
