version: '2'
services:
  proxy:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      config: |-
        defaults
            timeout client 5s
            timeout connect 120s
            timeout server 120s
      default_cert: EEA
      port_rules:
      - priority: 1
        protocol: https
        service: www-eea/apache
        source_port: 443
        target_port: 8443
      - priority: 2
        protocol: http
        service: www-eea/apache
        source_port: 80
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
